export const ACTIONS = {
    USER_SUBSCRIPTION_CHANGED: 'USER_SUBSCRIPTION_CHANGED',

    // settings
    TOGGLE_MOBILE_MENU: 'TOGGLE_MOBILE_MENU',
    CHECK_DEVICE_SIZE: 'CHECK_DEVICE_SIZE'
  };
  
  